Change the README.md
gabriel-antonelli/reservation-api pull request #108
Opened 2023-01-19 01:59 UTC by MatheusMoraes66

Create a new file Readme, now he has more information about the project.

- How to run the project.
- How to run test in the project.

2023-01-19 16:07 UTC, gabriel-antonelli requested changes

2023-01-19 16:07 UTC, gabriel-antonelli commented on README.md
> -## Description
Seria interessante ter a descrição

2023-01-19 16:07 UTC, gabriel-antonelli commented on README.md
> +- Node.js LTS v16 (ou qualquer versão superior)
Docker também

2023-01-19 16:07 UTC, gabriel-antonelli commented on README.md
> +Para conseguir rodar o projeto crie um arquivo `.env`, coloque dentro uma porta, se estiver com duvida tem um arquivo de exemplo `.env.example`
Precisa colocar mais lá também, dados do banco, secret, etc

2023-01-19 16:07 UTC, gabriel-antonelli commented on README.md
> +Há várias formas de rodar os testes, mas deixamos configurado alguns comandos para ajudar, o primeiro roda os testes unitários e os de integração.
O para rodar com coverage tambem: test:ci

2023-01-19 16:08 UTC, gabriel-antonelli reviewed
A descrição em e ingles é uma boa

2023-01-21 13:09 UTC, MatheusMoraes66 commented
Não seria melhor deixar o projeto com uma unico idioma? (Portugues ou Ingles)

2023-01-23 10:29 UTC, gabriel-antonelli commented
> 
O projeto todo está em inglês já
É possível usar dois readmes também

2023-02-05 13:54 UTC, MatheusMoraes66 commented
Da uma olhada agora por favor

2023-02-06 23:06 UTC, gabriel-antonelli approved these changes

2023-02-06 23:21 UTC, merged